### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by PouyaJalali** [INFO-511-F24/final-project-CodingWildcats#3]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Derek Rice - @derekriceX

- Shreya Kolte - @shreyakolte

- Pouya Jalali Khalilabadi - @PouyaJalali

- Describe the goal of the project.

   * What relationships are there between institutional characteristics and student aid, school spending and student outcomes (graduation rate, degree level, etc)?

- Describe the data used or collected.

   * https://collegescorecard.ed.gov/data/ 
   * Data was collected from 1996-2023 by the Department of Education by institutional reporting from U.S. schools. The dataset used for this project has been modified to be uploaded to GitHub. Observations include geographic data for each school, admission rates, institutional characteristics, enrollment, student aid, costs, and student outcomes.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

   *  They will hypothesize that student aid and school spending are correlated with student outcomes.

- Is there anything that is unclear from the proposal?

   *  The selected dataset is unclear since there are three datasets presented and no clear instructions which were selected
   * There is no clear approach to how they will answer the questions
   * Provided information is not enough/sufficient 

- Provide constructive feedback on how the team might be able to improve their project.

   * Better summarise/clarify on finalizing datasets and analysis plan.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

   * The relationships between institutional characteristics and student aid, school spending and student outcomes

- Provide constructive feedback on any issues with file and/or code organization.

   * More clarification on data selection and analysis plan
   * Organize the code to improve the readability 

- (Optional) Any further comments or feedback?

**Comment by DMStea** [comment]
Thank you for the feedback.
