### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by miguel-peralta** [INFO-511-F24/final-project-CodingWildcats#4]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Sarah Gilbride - @SarahGilbride
- Vera Jackson - @VeraJSolo
- Quinn Jones - @quinnajones
- Miguel Peralta - @miguel-peralta
- Cas Laskowski - @caslaskowski

- Describe the goal of the project.
A dataset has not been selected yet - the following are comments on the three datasets in the proposal.
**Dataset 1**: The team wants to understand how effective higher education is in the US, particularly relating to the relationship between student aid and school spending. The team hypothesized that student aid and school spending are correlated with student outcomes.
**Dataset 2**: The goal for this dataset is to understand if graduation rates and higher education preparation have a relationship with school demographics, funding, and class sizes. There is no hypothesis, but the Coding Wildcats team considers this question important because education quality is a factor in future success and overall life quality. 
**Dataset 3**: The team’s goal for using this dataset is to understand if it is useful for predicting the probability of a stroke based on demographics and medical history. There is no hypothesis, but the Coding Wildcats team considers this question important because identifying risk factors of a stroke can be used for prevention and more effective monitoring of patients. 

- Describe the data used or collected.
**Dataset 1**: Each row represents an institution and the columns contain aggregate information about that institution such as enrollment, admission rates, and cost. The team states that the dataset has been modified before it was uploaded to GitHub, but it is unclear from the proposal what changes have been made. 
**Dataset 2**: The data is from the Massachusetts Department of Education in 2017 and each row represents a public school, with columns containing information about that school such as location, demographics, expenditures, and test scores. The link for the data source provided in proposal.qmd gives a domain for School and District Profiles for the Massachusetts Department of Education, but it is not clear where on this website the dataset file was obtained. 
**Dataset 3**: The dataset is from Kaggle, the team cites a journal article as the source of the data but the Kaggle description of the dataset says that the source of the observations was confidential. The dataset described in the paper contains records for 29,072 patients with 12 attributes, while the dataset on Kaggle contains 5110 observations with 12 attributes. It is not clear if the team integrated data from both of these datasets. The dataset file contains various characteristics about the individuals such as age, other related conditions, marital status, and work, along with whether each individual had a stroke or not.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
For all three datasets, the research question has been specified but there is no plan for the specific approaches the team will be using to conduct analysis. 

- Is there anything that is unclear from the proposal?
The plan for analysis and hypotheses are unclear at this stage of the project.

- Provide constructive feedback on how the team might be able to improve their project.
There is no project abstract on the first page - this should be updated once the dataset is selected.
**Dataset 1**: No analysis plan was provided. The hypothesis could be more specific - what are the expected correlations? This could be an interesting conversation - maybe schools with schools that offer more student aid/spending are correlated to lower student debt or higher graduate income.
**Dataset 2**: The link provided goes to a general website for the Massachusetts Department of Education, but it isn’t clear where this specific file came from. No hypothesis, and no analysis plan was provided. If this becomes the selected dataset, it will be important to refrain from generalizing results when discussing data conclusions. Since this dataset is only looking at Public schools within one state across a single year, it may not necessarily be able to answer the general research question that was included in the proposal of whether there is a relationship between graduation rates and higher education preparation outside of this selective grouping of schools/year.
**Dataset 3**: It would be insightful to have some more context about the source of the dataset, especially regarding the inconsistency between the number of observations in the Kaggle dataset and the dataset described in the paper. Was there integration or filtering of these datasets performed before uploading to the repository? No hypothesis, and no analysis plan was provided. If this becomes the selected dataset, providing an analysis plan would be helpful. The research question asks whether it is possible to predict the possibility of an individual having a stroke based on their demographic information and medical history. Will this analysis include a model in order to predict this? Or will this project just look at correlation of the variables? Etc. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
We are interested in what statistical techniques will be used to analyze the dataset that the team chooses. 
**Dataset 1**: We are interested in seeing how statistical analysis could be used to investigate the research question. Correlation analysis could be of interest for this dataset.
**Dataset 2**: We are interested in a hypothesis for this research question and seeing how statistical analysis and/or modeling could give a better understanding of the dataset and the relationships within it. 
**Dataset 3**: We are interested in how a predictive model could be used for predicting a stroke, what type of model would be used, and the process of choosing an appropriate model. 

- Provide constructive feedback on any issues with file and/or code organization.
The files rendered correctly after cloning the repository. There were no issues with reproducibility at this stage of the project. Make sure to remove the extra dataset files and text related to datasets other than the chosen one for your project. There is also another dataset 1900_2021_DISASTERS.csv in the data folder that was not mentioned in the proposal. 

- (Optional) Any further comments or feedback?
If you decide to use the stroke dataset, we recommend considering the ethical implications of linking demographics to health outcomes as the data emerges from a system with health disparities that arise from demographics.

**Comment by DMStea** [comment]
Thank you for the feedback.
